### ISSUE TITLE
Remove backspace, delete, left arrow, etc. chords from practice csv before practicing

### ISSUE THREAD

**Issue by jdestgermain** [jdestgermain/CharaChorder-utilities#15]
I don't know if there are any other types of chords that aren't valid, but here are some examples in my chord library:

SPACERIGHT + DEL,DELDELDEL
SPACERIGHT + BKSP,bkspbkspbksp
SPACERIGHT + RT,rtrtrt
SPACERIGHT + LF,lflflf
BKSP + Space,bkspbkspbksp
BKSP + .,bkspbkspbkspbkspbkspbksp
BKSP + e,bkspbksp
BKSP + f,bkspbkspbkspbkspbkspbkspbksp
BKSP + h,bkspbkspbkspbkspbkspbkspbkspbkspbksp
BKSP + i,bkspbkspbkspbksp
BKSP + j,bkspbkspbkspbkspbkspbksp
BKSP + k,bkspbkspbkspbkspbkspbkspbksp
BKSP + l,bkspbkspbkspbksp
BKSP + m,bkspbkspbkspbkspbkspbkspbkspbkspbksp
BKSP + n,bkspbkspbkspbkspbksp
BKSP + o,bkspbkspbkspbkspbksp
BKSP + p,bkspbkspbkspbkspbkspbkspbkspbksp
BKSP + t,bkspbksp
BKSP + v,bkspbkspbkspbkspbkspbkspbkspbksp
RT + Space,rtrtrt
RT + .,rtrtrtrtrtrt
RT + e,rtrt
RT + f,rtrtrtrtrtrtrt
RT + h,rtrtrtrtrtrtrtrtrt
RT + i,rtrtrtrt
RT + j,rtrtrtrtrtrt
RT + k,rtrtrtrtrtrtrt
RT + l,rtrtrtrt
RT + m,rtrtrtrtrtrtrtrtrt
RT + n,rtrtrtrtrt
RT + o,rtrtrtrtrt
RT + p,rtrtrtrtrtrtrtrt
RT + t,rtrt
RT + v,rtrtrtrtrtrtrtrt
LF + Space,lflflf
LF + .,lflflflflflf
LF + e,lflf
LF + f,lflflflflflflf
LF + h,lflflflflflflflflf
LF + i,lflflflf
LF + j,lflflflflflf
LF + k,lflflflflflflf
LF + l,lflflflf
LF + m,lflflflflflflflflf
LF + n,lflflflflf
LF + o,lflflflflf
LF + p,lflflflflflflflf
LF + t,lflf
LF + v,lflflflflflflflf
DEL + Space,DELDELDEL
DEL + .,DELDELDELDELDELDEL
DEL + e,DELDEL
DEL + f,DELDELDELDELDELDELDEL
DEL + h,DELDELDELDELDELDELDELDELDEL
DEL + i,DELDELDELDEL
DEL + j,DELDELDELDELDELDEL
DEL + k,DELDELDELDELDELDELDEL
DEL + l,DELDELDELDEL
DEL + m,DELDELDELDELDELDELDELDELDEL
DEL + n,DELDELDELDELDEL
DEL + o,DELDELDELDELDEL
DEL + p,DELDELDELDELDELDELDELDEL
DEL + t,DELDEL
DEL + v,DELDELDELDELDELDELDELDEL

**Comment by bittujoju** [comment]
PR to fix this https://github.com/typing-tech/CharaChorder-utilities/pull/16/files
