### ISSUE TITLE
Practice: Start new session from keyboard

### ISSUE THREAD

**Issue by duianto** [jdestgermain/CharaChorder-utilities#32]
Suggestion:
Make it possible to start a new session from the keyboard. Like Monkeytype does.
By adding `TAB` as a shortcut to focus, the button: Start A New Practice Session

Focus the input box: Your Input
When the button is pressed: Start A New Practice Session

**Comment by jdestgermain** [comment]
Closed by 1cbb7a6ed6b269f88dbeddb0960f410fa49a51ff
