### ISSUE TITLE
Practice: Time Remaining text blinks and statistics increases

### ISSUE THREAD

**Issue by duianto** [jdestgermain/CharaChorder-utilities#34]
Bug:
After finishing a session.
Pressing any key in the input box, shows the text: Time Remaining: 0:00
for two seconds, below the input box,
then the text hides, and the top right text: All time statistics: 1 hours, 2 minutes
increases by the number of minutes of the previous session.

https://github.com/typing-tech/CharaChorder-utilities/assets/13420573/ee0abdcc-1190-4b2c-ac8f-f55ba26aada5

The video demonstrates a previous 2 minute session, but the same thing happens with a 1 minute session.

Expected:
The text: Time Remaining: 0:00
should probably only be visible while a session is in progress.

And the All time statistics should only increase after completing a real session.

**Comment by duianto** [comment]
The Time remaining text blinks once, if the practice minutes are set to zero,
The simplest solution might be to set the minimum allowed practice time to: 1

**Comment by jdestgermain** [comment]
Btw, is this all time stats real for you? 

![image](https://github.com/typing-tech/CharaChorder-utilities/assets/11359044/d9974579-a8f1-45d2-aaf6-80b715f5d013)

Over 17 hrs practice on this tool already?? lol or did you edit your local storage

I think you are right... I have been thinking about making it possible to go down to less than 60s though. Maybe I'll set a minimum of 10s or something.

**Comment by duianto** [comment]
😄 It's the bug, I kept practicing after the session ended (I remember seeing the chords practiced text saying at least 100), and every chord (including lot's of mistakes) increased the statistics minutes by one or two (when I started testing the bug).

**Comment by duianto** [comment]
Maybe one option could be to practice without a timer (infinitely) if the time is set to zero.

**Comment by jdestgermain** [comment]
Yeah, that could be interesting. Documenting that here and in the mean time, am pushing some changes to address some of what we talked about. 

https://github.com/typing-tech/CharaChorder-utilities/issues/35
