### ISSUE TITLE
Update chord-tools url, point to individual tools

### ISSUE THREAD

**Issue by duianto** [jdestgermain/CharaChorder-utilities#40]
Update the page: https://typing-tech.github.io/CharaChorder-utilities/#/chord-tools
So that it's possible to copy the URL directly to one of the four tools.

Currently, the URL doesn't change when one clicks on one of the tools.
The URL opens the first tool by default: Chord Viewer

This means that an extra instruction has to be included, for how to find the right tool.

**Comment by jdestgermain** [comment]
This now works, for example the new tool I just released can be accessed by: https://typing-tech.github.io/CharaChorder-utilities/#/chord-tools?tab=4
